In [925]:
import torch
torch.__version__

'1.13.1'

## Introduction to Tensors

### Creating tensors

In [926]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [927]:
scalar.ndim

0

In [928]:
# Get tensor back as python int
scalar.item()

7

In [929]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [930]:
vector.ndim

1

In [931]:
vector.shape

torch.Size([2])

In [932]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])

MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [933]:
MATRIX.ndim

2

In [934]:
MATRIX.shape

torch.Size([2, 2])

In [935]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [936]:
TENSOR.ndim

3

In [937]:
TENSOR.shape

torch.Size([1, 3, 3])

In [938]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [939]:
TENSOR[0][1]

tensor([4, 5, 6])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [940]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9812, 0.9682, 0.8077, 0.9293],
        [0.0854, 0.8333, 0.8413, 0.0739],
        [0.6649, 0.3683, 0.5335, 0.3250]])

In [941]:
random_tensor.ndim

2

In [942]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [943]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [944]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [945]:
ones.dtype

torch.float32

In [946]:
random_tensor.dtype 

torch.float32

### Creating a range of tensors and tensors-like

In [947]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [948]:
evens = torch.arange(2, 11, 2)
evens


tensor([ 2,  4,  6,  8, 10])

In [949]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [950]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], 
    dtype=None, # what datatype is the tensor (e.g. float32 or float16)
    device=None, # what device in your tensor on
    requires_grad=False, # whether or not to track gradients with this tensor's operations
)
float_32_tensor


tensor([3., 6., 9.])

In [951]:
float_32_tensor.dtype

torch.float32

In [952]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [953]:
float_16_tensor.dtype

torch.float16

In [954]:
result = float_16_tensor * float_32_tensor
result

tensor([ 9., 36., 81.])

In [955]:
result.dtype

torch.float32

In [956]:
int_64_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_64_tensor

tensor([3, 6, 9])

In [957]:
int_64_tensor * result

tensor([ 27., 216., 729.])

### Getting information from tensors

In [960]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.8415, 0.2684, 0.8558, 0.8144],
        [0.1662, 0.1493, 0.3109, 0.5205],
        [0.5403, 0.7889, 0.3123, 0.7133]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
