In [1578]:
import torch
torch.__version__

'1.13.1'

## Introduction to Tensors

### Creating tensors

In [1579]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [1580]:
scalar.ndim

0

In [1581]:
# Get tensor back as python int
scalar.item()

7

In [1582]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [1583]:
vector.ndim

1

In [1584]:
vector.shape

torch.Size([2])

In [1585]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])

MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [1586]:
MATRIX.ndim

2

In [1587]:
MATRIX.shape

torch.Size([2, 2])

In [1588]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [1589]:
TENSOR.ndim

3

In [1590]:
TENSOR.shape

torch.Size([1, 3, 3])

In [1591]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [1592]:
TENSOR[0][1]

tensor([4, 5, 6])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [1593]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1240, 0.2718, 0.3472, 0.4276],
        [0.2391, 0.9444, 0.7386, 0.6502],
        [0.4317, 0.8378, 0.6902, 0.4134]])

In [1594]:
random_tensor.ndim

2

In [1595]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [1596]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [1597]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [1598]:
ones.dtype

torch.float32

In [1599]:
random_tensor.dtype 

torch.float32

### Creating a range of tensors and tensors-like

In [1600]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [1601]:
evens = torch.arange(2, 11, 2)
evens


tensor([ 2,  4,  6,  8, 10])

In [1602]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [1603]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], 
    dtype=None, # what datatype is the tensor (e.g. float32 or float16)
    device=None, # what device in your tensor on
    requires_grad=False, # whether or not to track gradients with this tensor's operations
)
float_32_tensor


tensor([3., 6., 9.])

In [1604]:
float_32_tensor.dtype

torch.float32

In [1605]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [1606]:
float_16_tensor.dtype

torch.float16

In [1607]:
result = float_16_tensor * float_32_tensor
result

tensor([ 9., 36., 81.])

In [1608]:
result.dtype

torch.float32

In [1609]:
int_64_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_64_tensor

tensor([3, 6, 9])

In [1610]:
int_64_tensor * result

tensor([ 27., 216., 729.])

### Getting information from tensors

In [1611]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4094, 0.9715, 0.0424, 0.1978],
        [0.1872, 0.3812, 0.5088, 0.1398],
        [0.5803, 0.7019, 0.4778, 0.3850]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [1612]:
w_tensor = torch.rand(dtype=torch.float16, size=(3,4))
w_tensor

tensor([[0.4033, 0.9116, 0.8999, 0.6299],
        [0.8682, 0.8608, 0.6694, 0.0029],
        [0.3657, 0.2925, 0.1108, 0.4268]], dtype=torch.float16)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction 
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [1613]:
# Create a tensor 
tensor = torch.tensor([1, 2, 3])
tensor + 10 # add 10 to each element

tensor([11, 12, 13])

In [1614]:
tensor * 10

tensor([10, 20, 30])

In [1615]:
tensor

tensor([1, 2, 3])

In [1616]:
tensor - 2

tensor([-1,  0,  1])

In [1617]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [1618]:
torch.add(tensor, 100)

tensor([101, 102, 103])

### Matrix multiplication

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [1619]:
# Element wise multiplication
tensor = torch.tensor([1, 2, 3])
print(tensor * tensor)

tensor([1, 4, 9])


In [1620]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [1621]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [1622]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 962 µs, sys: 787 µs, total: 1.75 ms
Wall time: 1.03 ms


In [1623]:
%%time
value = torch.matmul(tensor, tensor)
print(value)

tensor(14)
CPU times: user 844 µs, sys: 497 µs, total: 1.34 ms
Wall time: 941 µs


In [1624]:
# matmul alternative
tensor @ tensor

tensor(14)

### Common errors: shape errors

two main rules that matrix multiplication needs to satisfy:
1. the **inner dimensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
2. the resulting matrix has the shape of **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [1625]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))
'''
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [674], line 1
----> 1 torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
'''
None

In [1626]:
res = torch.matmul(torch.rand(3, 2), torch.rand(2, 5))
print(res)
print(res.shape)

tensor([[1.2767, 1.1343, 0.4893, 0.7138, 0.6925],
        [1.2044, 1.0777, 0.4257, 0.6614, 0.6380],
        [1.3269, 1.1721, 0.5406, 0.7526, 0.7333]])
torch.Size([3, 5])


In [1627]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B)  # mm is alias for matmul

'''
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [1020], line 8
      2 tensor_A = torch.tensor([[1, 2],
      3                          [3, 4],
      4                          [5, 6]])
      5 tensor_B = torch.tensor([[7, 10],
      6                          [8, 11],
      7                          [9, 12]])
----> 8 torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
'''
None

To fix our tensor shape issues, we can manipulate the shaped of our one of the tensors using a transpose

In [1628]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [1629]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [1630]:
multiplied_result = torch.mm(tensor_A, tensor_B.T)
multiplied_result, multiplied_result.shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

### Finding the min, max, mean, sum etc (tensor aggregation)

In [1631]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [1632]:
torch.min(x)

tensor(0)

In [1633]:
x.min()

tensor(0)

In [1634]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [1635]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
# x.mean()
'''
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [1516], line 1
----> 1 x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
'''
None

In [1636]:
x.mean(dtype=torch.float32)

tensor(45.)

In [1637]:
x.type(torch.float32)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [1638]:
x.type(torch.float32).mean()

tensor(45.)

In [1639]:
x.sum()

tensor(450)