In [105]:
import torch
torch.__version__

'1.13.1'

## Introduction to Tensors

### Creating tensors

In [106]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [107]:
scalar.ndim

0

In [108]:
# Get tensor back as python int
scalar.item()

7

In [109]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [110]:
vector.ndim

1

In [111]:
vector.shape

torch.Size([2])

In [112]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])

MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [113]:
MATRIX.ndim

2

In [114]:
MATRIX.shape

torch.Size([2, 2])

In [115]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [116]:
TENSOR.ndim

3

In [117]:
TENSOR.shape

torch.Size([1, 3, 3])

In [118]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [119]:
TENSOR[0][1]

tensor([4, 5, 6])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [120]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4176, 0.6426, 0.9101, 0.7661],
        [0.5960, 0.8658, 0.9062, 0.4506],
        [0.1277, 0.7659, 0.7366, 0.5640]])

In [121]:
random_tensor.ndim

2

In [122]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)